version: 2.0
jobs:
  test:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout:              
      - run:
          name: The First Step
          command:  
            gradle test
      - store_test_results:
          path: build/test-results
  package:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout:              
      - run:
          name: The Second Step
          command:  
            gradle jar
      - store_artifacts:
          path: build/libs
          destination: prefix
  dockerize:
     machine: true
     steps:
       - checkout
       # Login to docker
       - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
       # build the application image
       - run: docker build -t pinconspiracy/circleapp:latest .
       # deploy the image
       - run: docker push pinconspiracy/circleapp:latest
workflows:
  version: 2
  three_job_flow:
    jobs:
      - test
      - package:
          requires:
            - test
      - dockerize
